
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.thermal]
			chocolate_cake = true
			spice_cake = true
			potion_cake = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

	[types.wood_type]

		[types.wood_type.biomesoplenty]
			fir = true
			pine = true
			maple = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.xkdeco]
			varnished = true
			mahogany = true
			ebony = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			rainbow_birch = true
			snowblossom = true
			null = true
			cypress = true
			fir = true
			pine = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true
			empyreal = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.xkdeco]
			white_cherry_blossom = true
			willow = true
			plantable = true
			peach_blossom = true
			cherry_blossom = true
			red_maple = true
			ginkgo = true
			orange_maple = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

