#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Sun May 03 13:45:39 CST 2026
farmersdelight=true
a=false
decorative_blocks=true
create=true
storagedrawers=true
