
[logbegone]
	regex = ["Disconnecting VANILLA connection attempt", "Channels "]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Collecting data for", "Loading JEI data for", "Couldn't parse data file", "Exception loading blockstate definition"]

