#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 05 05:30:55 GMT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.0.zip
enableShaders=false
