#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 06 15:00:35 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.0.zip
enableShaders=false
